### ISSUE TITLE
[feature] create pull request template

### ISSUE THREAD

**Issue by kan01234** [kan01234/ur-web-spider#63]
**Is your feature request related to a problem? Please describe.**
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kan01234** [comment]
not shown on creating PR...

**Comment by pqab** [comment]
still testing
